### ISSUE TITLE
Python: Traceback (most recent call last):

### ISSUE THREAD

**Issue by MultiplaysStudios** [Zi9/Blender-CarX-Mod-Tools#3]
Python: Traceback (most recent call last):
  File "C:\Users----i\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\zi_cx_tools\MapTools.py", line 274, in execute
    round(pnt.data.energy, 6),
AttributeError: 'Mesh' object has no attribute 'energy'

location: <unknown location>:-1

---------------
Happens when trying to export extra obj data

**Comment by Zi9** [comment]
Closing as stale. If the issue persists on the latest version of Blender (4.2) and the latest version of addon (1.4.0) then you can open a new issue and i'll take a look.
