### ISSUE TITLE
Tools dont show up 

### ISSUE THREAD

**Issue by eesaeesa** [Zi9/Blender-CarX-Mod-Tools#4]
After installing into blender and then searching up CarX nothing comes up . There should be a line that says 
Develpoement: zi9's carx mod tools . 
 Mine doesnt show up

![Blender Preferences 23_03_2023 16_48_39](https://user-images.githubusercontent.com/128730717/227276306-f8c455ad-5b72-41bf-a93d-6919ac218a30.png)

**Comment by Zi9** [comment]
Did you install the zip from the releases page?

[https://github.com/Zi9/Blender-CarX-Mod-Tools/releases/tag/v1.3.1](https://github.com/Zi9/Blender-CarX-Mod-Tools/releases/tag/v1.3.1)

![image](https://user-images.githubusercontent.com/17174057/227283245-55c6454c-ba7b-4c9c-9464-b5f35a7c8a1b.png)

**Comment by eesaeesa** [comment]
i will try install this one

**Comment by eesaeesa** [comment]
thank you it works

**Comment by eesaeesa** [comment]
umm actually when i press N on my keyboard with my tack selected it doesnt show any of the carx tools

**Comment by Zi9** [comment]
What version of blender are you using?

**Comment by eesaeesa** [comment]
the newest one

**Comment by eesaeesa** [comment]
2 days ago
but i know how it works

**Comment by eesaeesa** [comment]
3.4.1

**Comment by Zi9** [comment]
Closing as stale. If the issue persists on the latest version of Blender (4.2) and the latest version of addon (1.4.0) then you can open a new issue and i'll take a look.
